stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: devexp/ttyd:dev
      registry: 127.0.0.1:34062
timeout: 60
notification: {}
